//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedingtonMiniProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedingtonMiniProject.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P(A).
        /// </summary>
        public static string ADisplayedName {
            get {
                return ResourceManager.GetString("ADisplayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redington Mini Code Project.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P(B).
        /// </summary>
        public static string BDisplayedName {
            get {
                return ResourceManager.GetString("BDisplayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API controller returned -1, which means that exception occured during calculation. Check your probability.
        /// </summary>
        public static string CalculateProbability_ControllerException {
            get {
                return ResourceManager.GetString("CalculateProbability_ControllerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API controller did not return 200. Correct input parameters (this should appear as toast popup from materialize CSS deisgn).
        /// </summary>
        public static string CalculateProbability_JqonRequestFailed {
            get {
                return ResourceManager.GetString("CalculateProbability_JqonRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine with.
        /// </summary>
        public static string CombineWith {
            get {
                return ResourceManager.GetString("CombineWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either.
        /// </summary>
        public static string Either {
            get {
                return ResourceManager.GetString("Either", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcin Ceglarek For Redington Interviewers :).
        /// </summary>
        public static string FooterCopyrightText {
            get {
                return ResourceManager.GetString("FooterCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability calculator.
        /// </summary>
        public static string ProbabilityCalculator {
            get {
                return ResourceManager.GetString("ProbabilityCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
    }
}
